GET http://localhost:3000/contacts
###
GET http://localhost:3000/contacts/650f47d73b86321bfe6961b5
###
POST http://localhost:3000/contacts/ HTTP/1.1
content-type: application/json

{"firstName": "Jim", "lastName": "Person", "email": "example@email.com", "favoriteColor": "red", "birthday": "01/01/1001"}
###
PUT http://localhost:3000/contacts/651874bf2a8b3c11681affc0 HTTP/1.1
content-type: application/json

{"firstName": "Jim", "lastName": "YEET", "email": "example@email.com", "favoriteColor": "red", "birthday": "01/01/1001"}
###
DELETE http://localhost:3000/contacts/651873f4ac0deee6bb305d96 HTTP/1.1
###
GET https://contactscrud.onrender.com/contacts
###
GET https://contactscrud.onrender.com/contacts/650f47d73b86321bfe6961b5
###
POST https://contactscrud.onrender.com/contacts/ HTTP/1.1
content-type: application/json

{"firstName": "Jim", "lastName": "Person", "email": "example@email.com", "favoriteColor": "red", "birthday": "01/01/1001"}
###
PUT https://contactscrud.onrender.com/contacts/651901017e110080928621f3 HTTP/1.1
content-type: application/json

{"firstName": "Jim", "lastName": "YEET", "email": "example@email.com", "favoriteColor": "red", "birthday": "01/01/1001"}
###
DELETE https://contactscrud.onrender.com/contacts/651901017e110080928621f3 HTTP/1.1